- platform: template
  covers:
    cover_salle_a_manger:
      friendly_name: 'Volet - Salle à manger'
      open_cover:
        service: script.cover_salle_a_manger_up
      close_cover:
        service: script.cover_salle_a_manger_down
      stop_cover:
        service: script.cover_salle_a_manger_down
    cover_salon2:
      friendly_name: 'Volet - Salon 2'
      open_cover:
        service: script.cover_salon2_up
      close_cover:
        service: script.cover_salon2_down
      stop_cover:
        service: script.cover_salon2_down
