- platform: command_line
  covers:
    cover_salle_a_manger:
      friendly_name: 'Volet - Salle à manger'
      command_open: python_scripts/cover.sh 17
      command_close: python_scripts/cover.sh 27
      command_stop: python_scripts/cover.sh 27
    cover_salon2:
      friendly_name: 'Volet - Salon 2'
      command_open: python_scripts/cover.sh 24
      command_close: python_scripts/cover.sh 23
      command_stop: python_scripts/cover.sh 23
